apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    app.kubernetes.io/name: postgres
spec:
  ports:
  - name: postgres
    port: 5432
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-read
  labels:
    app: postgres
    app.kubernetes.io/name: postgres
    readonly: "true"
spec:
  ports:
  - name: postgres
    port: 5432
  selector:
    app: postgres
